"""Milestone 2: customers, service addresses, jobs, assignments, line items.

Revision ID: 0002_customers_and_jobs
Revises: 0001_initial_tenancy

Hand-written, not autogenerated. `alembic revision --autogenerate` proposed
dropping five objects it could not see in the ORM metadata, every one of them
load-bearing:

    ix_users_email_lower        case-insensitive uniqueness of email addresses
    uq_invitations_token_hash   uniqueness of invitation tokens
    ix_audit_log_tenant_created the index the audit screen actually queries on
    ck_tenants_*                the enum value guards

Functional indexes, partial indexes and constraints written as raw SQL are
invisible to autogenerate, so it reads them as drift and offers to remove them.
Accepting that diff would have allowed duplicate accounts differing only in
case, and duplicate invitation tokens. Every migration in this project is
reviewed by hand for that reason.
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "0002_customers_and_jobs"
down_revision = "0001_initial_tenancy"
branch_labels = None
depends_on = None

APP_ROLE = "serviceline_app"

NEW_TABLES = (
    "customers",
    "service_addresses",
    "jobs",
    "job_assignments",
    "job_line_items",
    "job_number_counters",
)

TIMESTAMPS = (
    sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        server_default=sa.text("now()"),
        nullable=False,
    ),
    sa.Column(
        "updated_at",
        sa.DateTime(timezone=True),
        server_default=sa.text("now()"),
        nullable=False,
    ),
)


def _id_column() -> sa.Column:
    return sa.Column(
        "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
    )


def upgrade() -> None:
    # ------------------------------------------------------------------
    # 1. Customers and the addresses work happens at
    # ------------------------------------------------------------------
    op.create_table(
        "customers",
        _id_column(),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("contact_name", sa.String(length=200), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        *TIMESTAMPS,
        sa.CheckConstraint("kind IN ('residential','company')", name="kind"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_customers_tenant_id_tenants",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_customers"),
    )
    op.create_index("ix_customers_tenant_id", "customers", ["tenant_id"])

    op.create_table(
        "service_addresses",
        _id_column(),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("line1", sa.String(length=200), nullable=False),
        sa.Column("line2", sa.String(length=200), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=60), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=False),
        # The authoritative timezone for anything scheduled here. See the note
        # on ServiceAddress.timezone: it lives on the address rather than the
        # company because one contractor works both sides of the Ohio/Indiana
        # line, where half of Indiana observes Central time.
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        *TIMESTAMPS,
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_service_addresses_tenant_id_tenants",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name="fk_service_addresses_customer_id_customers",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_service_addresses"),
    )
    op.create_index(
        "ix_service_addresses_tenant_id", "service_addresses", ["tenant_id"]
    )
    op.create_index(
        "ix_service_addresses_customer_id", "service_addresses", ["customer_id"]
    )
    # At most one primary address per customer. A partial unique index rather
    # than a constraint, because the rule only applies to the rows where
    # is_primary is true.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_service_addresses_one_primary
            ON service_addresses (customer_id)
            WHERE is_primary;
        """
    )

    # ------------------------------------------------------------------
    # 2. Jobs
    # ------------------------------------------------------------------
    op.create_table(
        "jobs",
        _id_column(),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("job_number", sa.String(length=20), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("service_address_id", sa.Uuid(), nullable=False),
        sa.Column("job_type", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column("customer_notes", sa.Text(), nullable=True),
        # The promise made to the customer, in their local wall clock.
        sa.Column("scheduled_date", sa.Date(), nullable=True),
        sa.Column("arrival_window_start", sa.Time(), nullable=True),
        sa.Column("arrival_window_end", sa.Time(), nullable=True),
        # The same window as absolute instants, for overlap detection. Wall
        # clock cannot be compared across timezones: 8-12 Eastern and 11-1
        # Central do not overlap, but their local times say otherwise.
        sa.Column("window_start_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_end_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        *TIMESTAMPS,
        sa.CheckConstraint(
            "job_type IN ('install','repair','maintenance','inspection',"
            "'emergency','other')",
            name="job_type",
        ),
        sa.CheckConstraint(
            "priority IN ('low','normal','high','emergency')", name="priority"
        ),
        sa.CheckConstraint(
            "status IN ('unscheduled','scheduled','en_route','in_progress',"
            "'complete','invoiced','closed','canceled')",
            name="status",
        ),
        # A window must end after it starts. Cheap to state, and it catches a
        # whole family of dispatcher typos at the database rather than in a
        # support call.
        sa.CheckConstraint(
            "arrival_window_start IS NULL OR arrival_window_end IS NULL "
            "OR arrival_window_end > arrival_window_start",
            name="window_order",
        ),
        sa.CheckConstraint(
            "window_start_utc IS NULL OR window_end_utc IS NULL "
            "OR window_end_utc > window_start_utc",
            name="window_utc_order",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_jobs_tenant_id_tenants",
            ondelete="CASCADE",
        ),
        # RESTRICT, not CASCADE: deleting a customer must not silently take
        # their job history -- and their invoices -- with it.
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name="fk_jobs_customer_id_customers",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["service_address_id"],
            ["service_addresses.id"],
            name="fk_jobs_service_address_id_service_addresses",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_jobs"),
        sa.UniqueConstraint("tenant_id", "job_number", name="uq_jobs_tenant_number"),
    )
    op.create_index("ix_jobs_tenant_id", "jobs", ["tenant_id"])
    op.create_index("ix_jobs_customer_id", "jobs", ["customer_id"])
    op.create_index("ix_jobs_service_address_id", "jobs", ["service_address_id"])
    op.create_index("ix_jobs_status", "jobs", ["status"])
    # The dispatch board's query: this tenant, this week, in order.
    op.create_index("ix_jobs_tenant_scheduled", "jobs", ["tenant_id", "scheduled_date"])
    # The overlap query for double-booking detection.
    op.create_index("ix_jobs_tenant_window", "jobs", ["tenant_id", "window_start_utc"])

    op.create_table(
        "job_assignments",
        _id_column(),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column(
            "is_lead", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        *TIMESTAMPS,
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_job_assignments_tenant_id_tenants",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name="fk_job_assignments_job_id_jobs",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["memberships.id"],
            name="fk_job_assignments_membership_id_memberships",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_job_assignments"),
        sa.UniqueConstraint(
            "job_id", "membership_id", name="uq_job_assignments_person"
        ),
    )
    op.create_index("ix_job_assignments_tenant_id", "job_assignments", ["tenant_id"])
    op.create_index("ix_job_assignments_job_id", "job_assignments", ["job_id"])
    op.create_index(
        "ix_job_assignments_membership_id", "job_assignments", ["membership_id"]
    )
    # Exactly one lead per job, enforced by the database rather than by
    # application convention. The original brief asked for several assigned
    # technicians and a board with one column each, without saying which column
    # a two-person job belongs in; this is the resolution made structural.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_job_assignments_one_lead
            ON job_assignments (job_id)
            WHERE is_lead;
        """
    )

    op.create_table(
        "job_line_items",
        _id_column(),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=10, scale=2), nullable=False),
        # Integer minor units. Floats and money do not mix.
        sa.Column("unit_price_cents", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        *TIMESTAMPS,
        sa.CheckConstraint("kind IN ('labor','part')", name="kind"),
        sa.CheckConstraint("quantity > 0", name="quantity_positive"),
        sa.CheckConstraint(
            "unit_price_cents IS NULL OR unit_price_cents >= 0",
            name="price_not_negative",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_job_line_items_tenant_id_tenants",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name="fk_job_line_items_job_id_jobs",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_job_line_items"),
    )
    op.create_index("ix_job_line_items_tenant_id", "job_line_items", ["tenant_id"])
    op.create_index("ix_job_line_items_job_id", "job_line_items", ["job_id"])

    # ------------------------------------------------------------------
    # 3. Job numbering
    # ------------------------------------------------------------------
    op.create_table(
        "job_number_counters",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("next_value", sa.Integer(), nullable=False, server_default="1"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_job_number_counters_tenant_id_tenants",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "year", name="pk_job_number_counters"),
    )

    # ------------------------------------------------------------------
    # 4. Search
    # ------------------------------------------------------------------
    # The brief asks for customer search by name, phone or address. Trigram
    # indexes make `ILIKE '%whit%'` an index scan instead of a sequential one,
    # which matters at a few thousand customers per tenant.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.execute(
        "CREATE INDEX ix_customers_name_trgm ON customers "
        "USING gin (name gin_trgm_ops);"
    )
    op.execute(
        "CREATE INDEX ix_customers_phone_trgm ON customers "
        "USING gin (phone gin_trgm_ops);"
    )
    op.execute(
        "CREATE INDEX ix_service_addresses_line1_trgm ON service_addresses "
        "USING gin (line1 gin_trgm_ops);"
    )

    # ------------------------------------------------------------------
    # 5. Privileges
    # ------------------------------------------------------------------
    op.execute(
        f"GRANT SELECT, INSERT, UPDATE, DELETE ON "
        f"{', '.join(NEW_TABLES)} TO {APP_ROLE};"
    )

    # ------------------------------------------------------------------
    # 6. Row-level security
    # ------------------------------------------------------------------
    # Same shape as milestone 1: ENABLE applies policies to everyone but the
    # table owner, FORCE removes that exemption too, and the policy is written
    # against the one definition of "the current tenant".
    for table in NEW_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")
        op.execute(
            f"""
            CREATE POLICY {table}_tenant_isolation ON {table}
                FOR ALL USING (tenant_id = app_current_tenant())
                WITH CHECK (tenant_id = app_current_tenant());
            """
        )


def downgrade() -> None:
    for table in reversed(NEW_TABLES):
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")
    op.drop_table("job_number_counters")
    op.drop_table("job_line_items")
    op.drop_table("job_assignments")
    op.drop_table("jobs")
    op.drop_table("service_addresses")
    op.drop_table("customers")
    # pg_trgm is left installed: other things may come to depend on it, and
    # dropping an extension is not the business of a table migration.
